version = 0.1
[default.deploy.parameters]
stack_name = "customers-service"
resolve_s3 = true
s3_prefix = "customers-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
